version: "3"
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - target: 5432
        published: ${DB_PORT:-5432}
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sqlpuzzle}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-sqlpuzzle}